name: zykli

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Match the Node.js version on EC2

    - name: Install Dependencies
      run: |
        npm install

    - name: Build React App
      run: |
        npm run build

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Deploy via SSH with Password Authentication
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@safalcode.com << 'EOF'
          cd /home/admin/web/zyk.li/public_html/
          rm -rf build
          mkdir build
          tar -xzf build.tar.gz -C build
          pm2 restart my-react-app || pm2 start serve -s build -p 3000 --name my-react-app
        EOF
