name: zykli

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14' # Match the Node.js version on EC2

    - name: Install Dependencies
      run: |
        npm install

    - name: Build React App
      run: |
        npm run build

    - name: zykli
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: safalcode.com
        username: admin
        key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCL/qpl6zCjBiCd/ZpDNpKPzjmcaw3k5PmIK3i7pDI1dwuFa///R1Ewn5RsVuY1OIorjr5FW3Ik+hw86qrYS0pHaIF29TE5EnRktgkfrxpAt5UlgGqBndzxpe+cG+IYb8XvD2dVKobRKAJ5/hVvtM0QzBuDXOs6ZYbGizOsdDkyY/ATJhQNA4yTwNhkdW+7WDFHPFKTJQAFuripbK19XRNxNJDmRkv687APxfJPPr07GNRHZQC30CAmeNd1HLQEqRXEch7YTk/QOntON6b2rmL2LoHZUh97oGKa92XLE4WRauXpM+znUkS6vUtLETOIDD343+7J5+Ret2zni7nNpxAgGGhITSKme/XDrIMj2BMpsbQjCj7MzMUmB56JVerFJh/U3lVbhdBtBK/3zD58uJq2yKseumoDUZ7T/8XHwvcXcmNKNohmjjG+4PiRugjvtiZ0cMl9bkQs93R8iBb4IZ1MrbcsCjrW8rtJ3TMArtKR/Ieb+zwQPopFvYb/peN/L8=
        script: |
          cd /home/admin/web/zyk.li/public_html/
          rm -rf build
          mkdir build
          tar -xzf build.tar.gz -C build
          pm2 restart my-react-app || pm2 start serve -s build -p 3000 --name my-react-app
