name: zykli

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Match the Node.js version on EC2

    - name: Install Dependencies
      run: |
        npm install

    - name: Build React App
      run: |
        npm run build
        ls -lh

    - name: List contents of build folder
      run: |
        ls -lh ./build  # Ensure the build folder contains files

    - name: Create build.tar.gz
      run: |
        if [ -d "./build" ]; then
          tar -czf build.tar.gz -C ./build .
        else
          exit 1
        fi
        ls -lh build.tar.gz

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Deploy via SSH with Password Authentication
      run: |
        sshpass -p "aruns777389@AKL" ssh -o StrictHostKeyChecking=no deployer@15.206.226.160 << 'EOF'
          mkdir -p /home/deployer/web/zyk.li/public_html/build
          cd /home/deployer/web/zyk.li/public_html/build
          rm -rf *
        EOF
        scp build.tar.gz deployer@15.206.226.160:/home/deployer/web/zyk.li/public_html/build/
        sshpass -p "aruns777389@AKL" ssh -o StrictHostKeyChecking=no deployer@15.206.226.160 << 'EOF'
          cd /home/deployer/web/zyk.li/public_html/build
          tar -xzf build.tar.gz
          pm2 restart my-react-app || pm2 start serve -s build -p 3000 --name my-react-app
        EOF