name: zykli

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Match the Node.js version on EC2

    - name: Install Dependencies
      run: |
        npm install

    - name: Build React App
      run: |
        npm run build
        # List the contents of the root directory to verify build folder
        ls -lh

    - name: List contents of build folder
      run: |
        ls -lh ./build  # Ensure the build folder contains files

    - name: Create build.tar.gz
      run: |
        # Check if the build folder exists
        if [ -d "./build" ]; then
          echo "Build folder exists, creating tar.gz"
          tar -czf build.tar.gz -C ./build .  # Create tar.gz from build folder
        else
          echo "Build folder does not exist"
          exit 1
        fi
        # Confirm tar file was created
        ls -lh build.tar.gz

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Deploy via SSH with Password Authentication
      run: |
        # SSH into the server and create the target directories
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@safalcode.com << 'EOF'

          mkdir -p /home/admin/web/zyk.li/public_html/build
          cd /home/admin/web/zyk.li/public_html/build
          rm -rf *
        EOF

        # SCP to transfer the tar.gz file
        scp build.tar.gz ${{ secrets.SSH_USERNAME }}@safalcode.com:/home/admin/web/zyk.li/public_html/build/

        # SSH into the server to extract the tar.gz file
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@safalcode.com << 'EOF'
          cd /home/admin/web/zyk.li/public_html/build
          tar -xzf build.tar.gz
          pm2 restart my-react-app || pm2 start serve -s build -p 3000 --name my-react-app
        EOF