name: zykli

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Match the Node.js version on EC2

    - name: Install Dependencies
      run: |
        npm install

    - name: Build React App
      run: |
        npm run build
        # Confirm that the build directory was created
        ls -lh build

    - name: Create build.tar.gz
      run: |
        # Confirm the build folder exists before running tar
        if [ -d "build" ]; then
          echo "Build folder exists, creating tar.gz"
          tar -czf build.tar.gz -C build .
        else
          echo "Build folder does not exist"
          exit 1
        fi

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Deploy via SSH with Password Authentication
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@safalcode.com << 'EOF'
          cd /home/admin/web/zyk.li/public_html/
          rm -rf build
          mkdir build
          scp /home/runner/work/zyk-front/zyk-front/build.tar.gz ${{ secrets.SSH_USERNAME }}@safalcode.com:/home/admin/web/zyk.li/public_html/build/
          tar -xzf /home/admin/web/zyk.li/public_html/build/build.tar.gz -C /home/admin/web/zyk.li/public_html/build
          pm2 restart my-react-app || pm2 start serve -s /home/admin/web/zyk.li/public_html/build -p 3000 --name my-react-app
        EOF